name: fastapi-redisearch-producs

services:
  python:
    build:
      context: .
      dockerfile: docker/Dockerfile.Python.Dev
    restart: unless-stopped
    ports:
      - 8400:8000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"